# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:latest

before_script:
  - python -V
  - pip install .
  - pip install pytest

test:
  script:
    - pytest integration_tests